### ISSUE TITLE
NOTE about issues

### ISSUE THREAD

**Issue by ghost** [p081/Project081#2]
**If you're having issues related to the website, do not post it here. This is only for the dmg itself and the patches!

Otherwise, feel free to post your issues here :)**

**Comment by M4rk91** [comment]
Hi, I installed the blue edition of last version (so the one also for iMac8,1) but after installing WI-FI is not working. I read about not installing AirPort 2010 update, but I haven't installed it and I haven't seen the "Ad-Hoc" button for the installation so I just installed normally. Thanks in advance for any reply.
Installed it on an 20-inch with Intel Core2Duo 2.66GHz & Radeon HD 2600 Pro. (Sorry for duplicate, I'll delete the one I created today, I didn't see I had to post here the issue instead then creating a new)
